// Safe bridge between the React UI and the main process.
import { contextBridge, ipcRenderer, webUtils } from 'electron';

const invoke = (channel: string, ...args: unknown[]) => ipcRenderer.invoke(channel, ...args);
const listen = (channel: string) => (cb: (payload: any) => void) => {
  const listener = (_e: unknown, p: unknown) => cb(p);
  ipcRenderer.on(channel, listener);
  return () => { ipcRenderer.removeListener(channel, listener); };
};

const api = {
  appInfo: () => invoke('app:info'),
  takePendingSort: () => invoke('app:takePendingSort'),
  detectGpu: () => invoke('gpu:detect'),
  getSettings: () => invoke('settings:get'),
  setSettings: (patch: unknown) => invoke('settings:set', patch),
  power: () => invoke('power:get'),
  openImages: () => invoke('dialog:openImages'),
  openFolder: (title?: string) => invoke('dialog:openFolder', title),
  pathKind: (p: string) => invoke('path:kind', p),
  inspectImage: (p: string) => invoke('image:inspect', p),
  imageSize: (p: string) => invoke('image:size', p),
  scanFolder: (p: string) => invoke('folder:scan', p),
  startJob: (req: unknown) => invoke('job:start', req),
  cancelJob: (id: string) => invoke('job:cancel', id),
  saveResult: (req: unknown) => invoke('result:save', req),
  queueList: () => invoke('queue:list'),
  queueCancel: (id: string) => invoke('queue:cancel', id),
  modelsStatus: () => invoke('models:status'),
  downloadModels: () => invoke('models:download'),
  updateStatus: () => invoke('update:get'),
  checkUpdates: () => invoke('update:check'),
  installUpdate: () => invoke('update:install'),
  sort: {
    status: (root: string) => invoke('sort:status', root),
    scan: (root: string) => invoke('sort:scan', root),
    pause: (paused: boolean) => invoke('sort:pause', paused),
    cancel: () => invoke('sort:cancel'),
    regroup: (fid: number) => invoke('sort:regroup', fid),
    review: (fid: number) => invoke('sort:review', fid),
    person: (pid: number) => invoke('sort:person', pid),
    rename: (pid: number, name: string, allowClash?: boolean) => invoke('sort:rename', pid, name, allowClash),
    merge: (from: number, into: number) => invoke('sort:merge', from, into),
    removeFace: (faceId: number) => invoke('sort:removeFace', faceId),
    split: (pid: number, faceIds: number[]) => invoke('sort:split', pid, faceIds),
    plan: (fid: number) => invoke('sort:plan', fid),
    apply: (fid: number) => invoke('sort:apply', fid),
    finish: (sortId: number) => invoke('sort:finish', sortId),
    undo: (sortId: number) => invoke('sort:undo', sortId),
    personFiles: (pid: number) => invoke('sort:personFiles', pid),
    dataSize: () => invoke('sort:dataSize'),
    deleteData: () => invoke('sort:deleteData'),
  },
  tidy: {
    status: (root: string) => invoke('tidy:status', root),
    scan: (root: string) => invoke('tidy:scan', root),
    results: (fid: number) => invoke('tidy:results', fid),
    organizePlan: (fid: number) => invoke('tidy:organizePlan', fid),
    setAsidePlan: (fid: number, kind: string, ids: number[]) => invoke('tidy:setAsidePlan', fid, kind, ids),
    apply: (fid: number) => invoke('tidy:apply', fid),
    undo: (sortId: number) => invoke('tidy:undo', sortId),
    trash: (fid: number, ids: number[]) => invoke('tidy:trash', fid, ids),
  },
  lib: {
    drives: () => invoke('lib:drives'),
    list: (dir: string) => invoke('lib:list', dir),
    hasMedia: (dirs: string[]) => invoke('lib:hasMedia', dirs),
    thumbs: (files: unknown[]) => invoke('lib:thumbs', files),
    pauseThumbs: (p: boolean) => invoke('lib:pauseThumbs', p),
    preview: (p: string) => invoke('lib:preview', p),
    search: (root: string, q: string) => invoke('lib:search', root, q),
    cancelSearch: () => invoke('lib:cancelSearch'),
    cacheSize: () => invoke('lib:cacheSize'),
    clearCache: () => invoke('lib:clearCache'),
  },
  player: {
    open: (p: string, caps: unknown) => invoke('player:open', p, caps),
    seek: (id: string, t: number, opts?: unknown) => invoke('player:seek', id, t, opts),
    close: (id: string) => invoke('player:close', id),
    subtitles: (id: string, track: string) => invoke('player:subtitles', id, track),
    loadSubtitle: (id: string) => invoke('player:loadSubtitle', id),
    frame: (p: string, t: number) => invoke('player:frame', p, t),
    position: (p: string, t: number, d: number) => invoke('player:position', p, t, d),
    playing: (b: boolean) => invoke('player:playing', b),
    recent: () => invoke('player:recent'),
  },
  tags: {
    labels: () => invoke('tags:labels'),
    forFiles: (files: unknown[]) => invoke('tags:forFiles', files),
    setStars: (files: unknown[], stars: number) => invoke('tags:setStars', files, stars),
    addLabel: (files: unknown[], name: string, color: string | null) => invoke('tags:addLabel', files, name, color),
    removeLabel: (paths: string[], id: number) => invoke('tags:removeLabel', paths, id),
    renameLabel: (id: number, name: string) => invoke('tags:renameLabel', id, name),
    setColor: (id: number, color: string | null) => invoke('tags:setColor', id, color),
    deleteLabel: (id: number) => invoke('tags:deleteLabel', id),
    query: (filter: unknown, text: string) => invoke('tags:query', filter, text),
    renameFile: (p: string, name: string) => invoke('tags:renameFile', p, name),
    moveFiles: (paths: string[]) => invoke('tags:moveFiles', paths),
    exportTo: (format: string) => invoke('tags:export', format),
    importFrom: () => invoke('tags:import'),
    findMoved: () => invoke('tags:findMoved'),
    missing: () => invoke('tags:missing'),
    backups: () => invoke('tags:backups'),
    backupNow: () => invoke('tags:backupNow'),
    restore: (file: string) => invoke('tags:restore', file),
    location: () => invoke('tags:location'),
    chooseLocation: () => invoke('tags:chooseLocation'),
    setLocation: (dir: string, mode: string) => invoke('tags:setLocation', dir, mode),
    testExport: (file: string) => invoke('tags:testExport', file),
    testImport: (file: string) => invoke('tags:testImport', file),
    playlists: () => invoke('tags:playlists'),
    savePlaylist: (name: string, filter: unknown, id?: number) => invoke('tags:savePlaylist', name, filter, id),
    deletePlaylist: (id: number) => invoke('tags:deletePlaylist', id),
    writeStatus: () => invoke('tags:writeStatus'),
    setWriteToFiles: (on: boolean) => invoke('tags:setWriteToFiles', on),
  },
  watch: {
    list: () => invoke('watch:list'),
    choose: () => invoke('watch:choose'),
    add: (dir: string) => invoke('watch:add', dir),
    remove: (dir: string) => invoke('watch:remove', dir),
    reindex: (dir: string) => invoke('watch:reindex', dir),
    query: (q: unknown) => invoke('watch:query', q),
  },
  onWatchStatus: listen('watch:status'),
  onWatchChanged: listen('watch:changed'),
  onWriteStatus: listen('tags:writeStatus'),
  onLibThumb: listen('lib:thumb'),
  onLibSearch: listen('lib:search'),
  onTidyProgress: listen('tidy:progress'),
  onTidyScanned: listen('tidy:scanned'),
  onTidyApply: listen('tidy:apply-progress'),
  showItem: (p: string) => invoke('shell:showItem', p),
  openPath: (p: string) => invoke('shell:openPath', p),
  openLogs: () => invoke('logs:open'),
  licences: () => invoke('licences:get'),
  /** Absolute path of a dropped file or folder. */
  pathForFile: (f: File) => webUtils.getPathForFile(f),
  onJobUpdate: listen('job:update'),
  onQueue: listen('queue:update'),
  onPower: listen('power:update'),
  onModels: listen('models:progress'),
  onUpdate: listen('update:status'),
  onSortProgress: listen('sort:progress'),
  onSortScanned: listen('sort:scanned'),
  onApplyProgress: listen('sort:apply-progress'),
  onOpenSort: listen('open:sort'),
};

export type PixHavenApi = typeof api;
contextBridge.exposeInMainWorld('clearup', api);
